language: java
addons:
  apt:
    packages:
    - xmlstarlet
    - graphviz
jdk:
- oraclejdk11
after_success:
- wget -O settings.xml https://raw.githubusercontent.com/pousse-cafe/pousse-cafe-deploy/master/snapshot_release_settings.xml
- "./can_auto_deploy.sh && mvn deploy --settings settings.xml"
env:
  global:
  - secure: SWU7Hyt3/tcyMGtm5V584DhU7C7ifG18xzzuWb+D2Sgg/kP2Wi46m564Aqvq8KOTGHWO1b8nHWea0GIXkTm3EbGEPvPD12an00ZsdEN5c7YNnWTRKC0sdXawEvcwoliZ9fLgnGFj4ZsWXRQXeDMEIl/HiLzZB2L89pCBaNz3o44Uo2LDFcE1RpSv0f22h1CEh+cNmI1t/YPF8LIQe54VXBpBxKDaT1vBJfp2CmJXh+LZcYnkOYhchC0lp74ielH+Dh1oGOfdz05myUY9HQNaAbFsl1VFNabMHg5Ux5hblHJcYVZqVY74CG3gkCv61NBA5GM6+avy3/R39ebiguJKwkqSgUGHcMSUT5ytB29RMbgT+lKqisfagIv2K+14oXcBF3FTIPy/HrPM8pq6MA74WZ/5hy9hFu8jobaeyCzn+tR34+rfy3kPtrdOuJ4qW0+Hask7DK98x7IdAnu++vON662LmLYImR8vEFZF5KF4R+/WkS4ZxXq5VUTq2NiL2t9zhFA/AbIeuu5u8/JPeQeH6W2VVxKw/He40JPr+eaxY+2LZWG1LVMPGHORPFd1tImBm5XetilUiM4dN8MrukPJTccPj8wAv9++phv+5aLxcYbe0RdQD03dwfeSNJ5GtZbBQvdsXIEMvUHRl0fijioD6JpKNK2LGtmj1rZtJjux7cI=
  - secure: H9+VxoTUo9n1RPKFSFVd8MoBoIs0CzwZLVOElPKSjsy3ilaR+7j5nlS+pZkyILpogsecemSJp1tueG76oOwNtC1242ujQAKxIzWBYBnfJXii6g0wj8qOI5jU1Rfoh96Rs/Fr9sF2HRWUjKKzZl52zD+zvOTEMu2dfVRpNqm5u4SDhp8uN6TfFia5cCyDLScowN3HGw4q6lTy/J6kWFB1PKx53V5VrXHr9v6QvXriq22Zsjqn1j+1WJU6WGTzVq759Qlk2JUx4Z3+X67RrwYuucUCTCF4iQhXPo3rZfQcNRucHmkpGixCSFOlfQSSz8Cb1nLcnQ36YDRmgDV/YhH4Co1B9Zid9qjLAG9PtGaTBnaNyqScQWD73DGE1A7C4OOdTkjYSCgtc4vs1O53PXf3H1W62qJDpJBYCqgThMCdZNPLgJJ0Ou4wPvHmrUbWRNRVKpPrV67HCJOWVIcu9G0CdTHjBAlHpTv0xNTo+NVp3W5E/MJ3QSFI5B+an+b7cVRQWXwyOjNySCdxEAwa1oKJcaqqyM6boMsndSvp2vb54yq9TEbmpujFqp/E1vvinwjHDLd4Osf+i87MGjBhPsmnZRZr+oFSFAkMIhoYRxtA0y1VbwS95WQzPhPDXsLuly+I4gkYYpJMVsU7dQhYLDgvzCwKDptTBgAUsOmQ48ahMTo=
